#!/bin/bash

ulimit -s unlimited

SREAD=../stencil_read
RUNDIR=`pwd`

BANKS=16
CAPACITY=8
LINKS=8
BSIZE=64
QDEPTH=64
XDEPTH=128
VAULTS=64
DRAMS=20
CLOCKGHZ=2.0
ARRAYWIDTH=20
ARRAYHEIGHT=20
ARRAYDEPTH=20
THREADS=16
CORES=2
LIBSRC=../../../cmc/

echo "Executing $SREAD -L $LIBSRC -b $BANKS -c $CAPACITY -d $DRAMS -l $LINKS -m $BSIZE -n 1 -q $QDEPTH -v $VAULTS -x $XDEPTH -i $ARRAYWIDTH -j $ARRAYHEIGHT -k $ARRAYDEPTH -t $THREADS -C $CLOCKGHZ -o $CORES"


$SREAD -L $LIBSRC -b $BANKS -c $CAPACITY -d $DRAMS -l $LINKS -m $BSIZE -n 1 -q $QDEPTH -v $VAULTS -x $XDEPTH -i $ARRAYWIDTH -j $ARRAYHEIGHT -k $ARRAYDEPTH -t $THREADS -C $CLOCKGHZ -o $CORES

